#!/usr/bin/env bash

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
clear='\033[0m'

find . -type f -name "temp.*" -delete
find . -type f -name "out.*" -delete

TMP=temp.$$
OUT=out.$$

for TEST in tests/t_*.bas
do
  TITLE=`grep -i ' rem ' ${TEST} | sed 's/.* rem //i'`

  echo -e "${blue}${TEST}${clear} ${TITLE}"

  NAME=`basename ${TEST} .bas`
  LIST="tests/${NAME}.out"

  ./dbc --input ${TEST} --output ${TMP}
  if [ $? -ne 0 ]; then
    echo -e "  ${red}Failed to compile${clear}"
  else
    if [ -e ${LIST} ]; then
      ./dcpu --input ${TMP} > ${OUT}
      diff ${LIST} ${OUT} > /dev/null
      if [ $? -eq 0 ]; then
        echo -e "  ${green}Ok${clear}"
      else
        echo -e "  ${red}Failed${clear}"
        echo
        echo "  ${blue}Expected${clear}"
        cat ${LIST}
        echo
        echo "  ${blue}Got${clear}"
        cat ${OUT}
        echo
      fi
    else
      echo -e "  ${yellow}No output for ${TEST} ${LIST}${clear}"
    fi
  fi
done

rm ${TMP}
rm ${OUT}
